### ISSUE TITLE
The atomspace-explorer doesnt render due to some issues, and new features

### ISSUE THREAD

**Issue by mjsduncan** [opencog/atomspace-explorer#6]
The atomspace-explorer doesnt render due to some issues, and new features are added.

see commits in fork https://github.com/edyirdaw/atomspace-explorer/tree/fixes for fixes

**Comment by linas** [comment]
I just created pull req #7 to pick up @edyirdaw changes.  I won't merge until either you or @edyirdaw agree that this is the correct set of changes to apply.   Or maybe I should just merge now, and then hold my breath, in case there are other changes that are needed?

In principle, @edyirdaw should have created the pull req, back when he was actually making these changes. I have no problem if he takes over management of this repo, I can grant read/write permissions. ... Hmm. I'll grant read-write permissions now I think I have that power?

**Comment by linas** [comment]
I merged. You and @edyirdaw now have write access.

If there's additional work to be done, top priority would be to get rid of the json format and swap to atomese: this would make it run faster better stronger.

**Comment by edyirdaw** [comment]
I have modified mike's issue title and detailed description to be more accurate.

**Comment by linas** [comment]
closing fixed,
